use_frameworks!

target 'FAQUtility_Example' do
  pod 'FAQUtility', :path => '../'

  target 'FAQUtility_Tests' do
    inherit! :search_paths

    
  end

    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end

end
